### ISSUE TITLE
RTX Tracking: Finding the Correct 'ExpressionApp.exe' Path , But Tells Me That's Still Incorrect

### ISSUE THREAD

**Issue by MonoCycloptic** [DrBomb/ExpressionAppBridge#3]
Hello! I'm having trouble with the RTX Tracking option. 
I'm using it for VSeeFace. I got Vtube Studio and the Vtube Studio - NVIDIA Broadcast Tracker installed and everything works great from there.

But when it comes to selecting the RTX Tracking, it's redirecting to a non existing path: _"D:\SteamLibrary\steamapps\common\VTube Studio\VTube Studio_Data\StreamingAssets\MXTracker"_ 

So I searched and found the .exe that it was asking for on the following path: _"C:\Program Files (x86)\Steam\steamapps\common\VTube Studio\VTube Studio_Data\StreamingAssets\MXTracker\ExpressionApp.exe"_

Yet, it still tells me that "...does not contain ExpressionApp.exe!" while it's clearly there?

![image](https://github.com/user-attachments/assets/bc286dd3-ad6d-4600-917b-b51e10daba93)
![image](https://github.com/user-attachments/assets/ef698c9f-e44b-4aed-a13f-e959d4453700)
![image](https://github.com/user-attachments/assets/75fb2b4b-279a-41a8-87f7-e2c3883d4f53)

Am I missing something and doing it wrong? or is it a bug? Please let me know.

Specs for reference:
Laptop: Lenovo Slim 7 ProX 14ARH7
Processor: AMD Ryzen 7 6800HS Creator Edition   3.20 GHz
Installed RAM: 16.0 GB (13.7 GB usable)
System type: 64-bit operating system, x64-based processor
OS: Windows 11 Home (up to date)
Graphic driver: Nvidia Geforce RTX Studio Vers. 561.09 (up to date)

**Comment by DrBomb** [comment]
Hello! The problem is that you're giving the program the complete path to the .exe while the program asks the path to the **folder** where the .exe is located.

Try `C:\Program Files (x86)\Steam\steamapps\common\VTube Studio\VTube Studio_Data\StreamingAssets\MXTracker` instead.

In hindsight, I should've assumed someone could input the complete path, maybe thats something I could add if I ever return to this little program.

Anyways, let me know if it works, if not, drop me a DM in my twitter @Dr_Bomb and I'll help you out.

**Comment by MonoCycloptic** [comment]
OOOH, that actually worked! Now I feel silly. 

Thanks for clarifying! ^^
